### Test ingest by IDs
POST http://localhost:8000/ingest
Content-Type: application/json

{
  "ids": [632]
}

### Test ingest by date range
POST http://localhost:8000/ingest/date-range
Content-Type: application/json

{
  "from_date": "2025-03-01",
  "to_date": "2025-03-07"
}

### Test parse by IDs
POST http://localhost:8000/parse
Content-Type: application/json

{
  "ids": [1512]
}

### Test parse by date range
POST http://localhost:8000/parse/date-range
Content-Type: application/json

{
  "from_date": "2025-03-01",
  "to_date": "2025-03-07"
}

### Test chat
POST http://localhost:8000/chat
Content-Type: application/json

{
  "question": "2026학년도 1학기 교환학생 신청 기간이 언제야??",
  "conversation_id": "aaaa"
}
