### Test ingest by IDs
POST http://localhost:8000/ingest
Content-Type: application/json

{
  "ids": [1512]
}

### Test ingest by date range
POST http://localhost:8000/ingest/date-range
Content-Type: application/json

{
  "from_date": "2025-01-01",
  "to_date": "2025-09-17"
}

### Test parse by IDs
POST http://localhost:8000/parse
Content-Type: application/json

{
  "ids": [1512]
}

### Test parse by date range
POST http://localhost:8000/parse/date-range
Content-Type: application/json

{
  "from_date": "2025-03-01",
  "to_date": "2025-03-07"
}

### Test chat
POST http://localhost:8000/chat
Content-Type: application/json

{
  "question": "올해 취업 박람회에 참여해 마케팅 관련 직무 멘토링을 듣고 싶은데 일시와 참여 기업 알려줘.",
  "conversation_id": "aaaa"
}
